name: site
version: 0.1
synopsis: esrh's site
author: esrh
maintainer: esrh@gatech.edu
license: GPL-3

dependencies:
  - base >= 4.7 && < 5
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  site:
    main: site.hs
    source-dirs: "."
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blaze-html
      - bytestring
      - containers
      - directory
      - filepath
      - hakyll
      - hakyll-sass
      - language-javascript
      - lens
      - pandoc
      - pandoc-types
      - pretty-terminal
      - skylighting
      - skylighting-core
      - split
      - text
      - time
      - xml
