[buildPlans.iosevka-hane-sans]
family = "Iosevka Hane Sans"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-hane-sans.variants.design]
capital-d = "more-rounded-serifless"
capital-z = "straight-serifless-with-horizontal-crossbar"
capital-q = "crossing"
capital-w = "curly"
f = "flat-hook-tailed"
g = "single-storey-serifless"
i = "serifed-flat-tailed"
k = "cursive-bottom-right-serifed"
l = "serifed-flat-tailed"
t = "flat-hook-short-neck"
y = "straight-turn"
j = "flat-hook-serifed"
r = "corner-hooked"
two = "straight-neck"
four = "closed"
seven = "bend-crossbar"
eight = "two-circles"
underscore = "high"
brace = "straight"
lower-lambda = "straight-turn"
zero = "slashed"
asterisk = "hex-low"
ampersand = "closed"
at = "threefold"
percent = "rings-continuous-slash"
ascii-single-quote = "straight"
ascii-grave = "straight"

  [buildPlans.iosevka-hane-sans.ligations]
  inherits = "dlig"

[buildPlans.iosevka-hane-sans.widths.normal]
shape = 600
menu = 5
css = "normal"
